name: Copy and rename rules.txt  
  
on:  
  push:  
    paths:  
      - '**/*.txt'  
  
jobs:  
  copy_and_rename:  
    name: Copy and rename rules.txt  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
      - name: Set up Python 3.8  
        uses: actions/setup-python@v2  
        with:  
          python-version: 3.8  
      - name: Run Python script  
        run: |  
          python copy_rules.py
